name: بیگانه

description: یادداشت‌های روزانه یک نِرد پیرامون موضوعات جالب توجه برای نتیجه‌گیری‌های عمیق

url: https://biganeh.com

author: بیگانه

permalink: /:title

encoding: UTF-8

kramdown:
   syntax_highlighter_opts:
      disable : true

feed:
  excerpt_only: true

gems:
  - jekyll-sitemap
  - jekyll-feed
