name: احسایدر

description: احسایدر بیشتر محل یادگیری‌های شخصی خودمه و البته که آنلاینه و خوشحال می‌شم اگه واسه بقیه هم کاربردی داشته باشه

url: https://ehsaider.ir

author: احسان چهری

permalink: /:title

encoding: UTF-8

kramdown:
   syntax_highlighter_opts:
      disable : true

feed:
  excerpt_only: true

gems:
  - jekyll-sitemap
  - jekyll-feed
