name: بیگانه

description: وبلاگ بیگانه دفترچه یادداشتم درباره اسامی بحث برانگیز دنیای اطراف منه و البته راه حل خودم برای فرار از ویکی پدیا

url: https://biganeh.com

author: biganeh.com

permalink: /:title

encoding: UTF-8

kramdown:
   syntax_highlighter_opts:
      disable : true

feed:
  excerpt_only: true

gems:
  - jekyll-sitemap
  - jekyll-feed
