name: وبلاگ احسان چهری

description: روزنوشت‌ها و یادداشت‌های احسان چهری، از سئو تا شطرنج

avatar: images/ehsaider.png

permalink: /:title

footer-links:
  twitter: ehsanchehri
  rss: feed.xml

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-feed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 50

paginate_path: /page:num

lang: fa_IR

twitter:
  username: ehsanchehri
  card: summary

timezone: Iran/Tehran

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
