name: احسایدر

description: وبلاگ احسایدر

url: https://ehsaider.ir

author: احسان چهری

permalink: /:title

encoding: UTF-8

kramdown:
   syntax_highlighter_opts:
      disable : true

feed:
  excerpt_only: true

whitelist:
  - jekyll-redirect-from

title: My amazing post
redirect_from:
  - /65
  - /99

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
