name: احسایدر

description: روزنوشت‌ها و یادداشت‌های گاه به گاه احسان چهری

avatar: https://ehsaider.ir/images/ehsaider.png

url: https://ehsaider.ir

permalink: /:title

encoding: UTF-8

footer-links:
  twitter: ehsanchehri
  rss: feed.xml

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

compress_html:
  clippings: all
  comments: [""]
  endings: []
  blanklines: false
  profile: false
  ignore:
    envs: []

sass:
  style: :compressed

gems:
  - jekyll-sitemap
  - jekyll-feed
