name: احسایدر

description: یادداشت‌هایی پیرامون سئو و طراحی سایت

url: https://ehsaider.ir

permalink: /:title

encoding: UTF-8

compress_html:
  clippings: all
  ignore:
    envs: development

kramdown:
   syntax_highlighter_opts:
      disable : true

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

redirect_from:
  - /p2
  - /tempo

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
